// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdN7Z3BXFqCR7lPbw5WKEuXXjAEkOvqYM',
    appId: '1:638488476673:web:592e6ddeeb170e539e9400',
    messagingSenderId: '638488476673',
    projectId: 'projectalpha-5c223',
    authDomain: 'projectalpha-5c223.firebaseapp.com',
    storageBucket: 'projectalpha-5c223.appspot.com',
    measurementId: 'G-E6CJBMG394',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGaSxufDSYb_oHI332wfvcIcSgJfsHc7o',
    appId: '1:638488476673:android:c0acf8e7dc5982139e9400',
    messagingSenderId: '638488476673',
    projectId: 'projectalpha-5c223',
    storageBucket: 'projectalpha-5c223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC09d25zgVtU6Qqb-RBJ-Z0PQFWEbhSZrA',
    appId: '1:638488476673:ios:2f7e7458afe3d1b59e9400',
    messagingSenderId: '638488476673',
    projectId: 'projectalpha-5c223',
    storageBucket: 'projectalpha-5c223.appspot.com',
    iosClientId: '638488476673-ltbukkekkpt9gh9bqn9tv3t141ibrbql.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectalpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC09d25zgVtU6Qqb-RBJ-Z0PQFWEbhSZrA',
    appId: '1:638488476673:ios:2f7e7458afe3d1b59e9400',
    messagingSenderId: '638488476673',
    projectId: 'projectalpha-5c223',
    storageBucket: 'projectalpha-5c223.appspot.com',
    iosClientId: '638488476673-ltbukkekkpt9gh9bqn9tv3t141ibrbql.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectalpha',
  );
}
